INSERT INTO users (name, age) VALUES ("Linus Torvalds", 42);
INSERT INTO users (name, age) VALUES ("Richard Stallman", 50);
INSERT INTO users (name, age) VALUES ("Popey", 28);
INSERT INTO users (name, age) VALUES ("Martin Wimpress", 35);
INSERT INTO users (name, age) VALUES ("Johnny Ruby", 58);
INSERT INTO users (name, age) VALUES ("Paulie Python", 23);
INSERT INTO users (name, age) VALUES ("Charlie Chair", 65);
INSERT INTO users (name, age) VALUES ("Lucinda Nishida", 11);
INSERT INTO users (name, age) VALUES ("Claris Grubaugh", 22);
INSERT INTO users (name, age) VALUES ("Latarsha Courchesne", 33);
INSERT INTO users (name, age) VALUES ("Rachell Whicker", 44);
INSERT INTO users (name, age) VALUES ("Mallory Cogdill", 55);
INSERT INTO users (name, age) VALUES ("Marcellus Niswander", 66);
INSERT INTO users (name, age) VALUES ("Lu Shuford", 77);
INSERT INTO users (name, age) VALUES ("Martha Yoho", 88);
INSERT INTO users (name, age) VALUES ("Krystin Bosworth", 99);
INSERT INTO users (name, age) VALUES ("Micha Suits", 12);
INSERT INTO users (name, age) VALUES ("Renita Rhymes", 23);
INSERT INTO users (name, age) VALUES ("Wanetta Wohl", 34);
INSERT INTO users (name, age) VALUES ("Florine Fullam", 45);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Reject Reality", "Music", 20000, "04/01/2017", "04/01/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Substitute Our Own", "Writing", 100000, "01/02/2016", "01/03/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Monster Cans", "Electronics", 200, "02/10/2010", "03/22/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Clamshell Powercord", "Photography", 50000, "05/10/2015", "06/22/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Inverted Couches", "Music", 200000, "07/10/2016", "08/22/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Inside Up", "Writing", 1000000, "09/10/2014", "10/23/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Outside Down", "Photography", 10000000, "10/22/2011", "11/02/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Darkstar", "Electronics", 500, "12/01/2010", "01/20/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("See-Four", "Video", 20000000, "01/01/2009", "01/01/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Binary Clock", "Music", 15000, "05/10/2014", "09/22/2017");

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1100, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1200, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1300, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1400, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1500, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1600, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1700, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1800, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1900, 19, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 10);